{{- if .Values.deploy.mongo }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.services.mongo.name }}-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.services.mongo.userName | toString | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.services.mongo.userPassword | toString | b64enc | quote }}
{{- end}}