{{- if .Values.deploy.mongo }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mongo.name }}-{{ .Values.werf.env }}-service
  labels:
    app: {{ .Values.services.mongo.name }}
    env: {{ .Values.werf.env }}
spec:
  selector:
    app: {{ .Values.services.mongo.name }}
    env: {{ .Values.werf.env }}
  ports:
    - name: mongo-port
      protocol: TCP
      port: {{ .Values.services.mongo.port }}
      targetPort: {{ .Values.services.mongo.port }}
{{- end }}
