{{- if .Values.deploy.mongo }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.services.mongo.name }}-statefulset
  labels:
    app: {{ .Values.services.mongo.name }}
    env: {{ .Values.werf.env }}
spec:
  serviceName: {{ .Values.services.mongo.name }}-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.mongo.name }}
      env: {{ .Values.werf.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.mongo.name }}
        env: {{ .Values.werf.env }}
        logging: disabled
    spec:
      imagePullSecrets:
        - name: registry
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      containers:
        - name: {{ .Values.services.mongo.name }}
          image: {{ .Values.werf.image.mongo }}
          ports:
            - name: mongo-port
              containerPort: {{ .Values.services.mongo.port }}
          envFrom:
            - secretRef:
                name: {{ $.Values.services.mongo.name }}-secret
          {{- include "mongo.livenessProbe"  . | indent 10 }}
          {{- include "mongo.readinessProbe" . | indent 10 }}
          volumeMounts:
            - name: {{ .Values.services.mongo.volumeName }}-{{ .Values.werf.env }}
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.services.mongo.volumeName }}-{{ .Values.werf.env }}
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: {{ .Values.services.mongo.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.services.mongo.storageSize }}
{{- end }}