{{- if .Values.deploy.rabbitmq }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.services.rabbitmq.name }}-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.services.rabbitmq.user | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.services.rabbitmq.password | b64enc | quote }}
{{- end }}