{{- if .Values.deploy.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.werf.name }}-{{ .Values.werf.env }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "cloudflare"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP  $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
    {{- if eq .Values.global.auth true }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
spec:
  tls:
  - hosts:
      - {{ include "project.domain" . }}
    secretName: {{ .Values.werf.name }}-{{ .Values.werf.env }}-ssl
  rules:
  - host: {{ include "project.domain" . }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.services.api.name }}-{{ .Values.werf.env }}-service
              port:
                number: {{ .Values.services.api.port }}
        - path: /rabbitmq(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.services.rabbitmq.name }}-{{ .Values.werf.env }}
              port:
                number: {{ .Values.services.rabbitmq.port_ui }}
{{- end }}
{{- if .Values.global.www }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.werf.name }}-{{ .Values.werf.env }}-with-www
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'www.{{ .Values.global.url }}') {
        return 301 https://{{ .Values.global.url }}$request_uri;
      }
spec:
  tls:
  - hosts:
      - www.{{ .Values.global.url }}
    secretName: {{ .Values.werf.name }}-cf-ssl
  rules:
  - host: www.{{ .Values.global.url }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.werf.name }}-{{ .Values.werf.env }}
              port:
                number: {{ $.Values.global.port }}
{{- end }}