apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-brn-ssh-key
type: Opaque
data:
  id_rsa: {{ .Values.mongobrnsshkey }}

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  host:       {{ .Values.global.minio.host      | b64enc | quote }}
  user:       {{ .Values.global.minio.user      | b64enc | quote }}
  bucket:     {{ .Values.global.minio.bucket    | b64enc | quote }}
  password:   {{ .Values.global.minio.password  | b64enc | quote }}
  access-key: {{ .Values.global.minio.accessKey | b64enc | quote }}
  secret-key: {{ .Values.global.minio.secretKey | b64enc | quote }}

---
{{ if .Values.global.auth }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
data:
  auth: {{ .Values.global.credentials }}
{{ end }}
